### ISSUE TITLE
Doesn't work with Firebase

### ISSUE THREAD

**Issue by marcelmika** [react-workspaces/react-workspaces-playground#10]
First, thanks for a great lib!
We almost made it work until we had to include Firebase as a dependency.

```
cd packages/apps/app-one
yarn add firebase@6.2.0
```

As you can see here: https://www.npmjs.com/package/firebase#npm-bundler-browserify-webpack-etc you simply import a firebase package:

```js
// In your code, you can access Firebase using:
var firebase = require('firebase');
var app = firebase.initializeApp({ ... });

// If you are using ES6 imports or TypeScript:
import * as firebase from 'firebase';
var app = firebase.initializeApp({ ... });
```

Unfortunately, when we do it we get the following error:
```
TypeError: util.inherits is not a function
```
![Screen Shot 2019-06-17 at 14 24 41](https://user-images.githubusercontent.com/3537470/59604193-ba6ec480-910b-11e9-95b7-1f1d1f94492f.png)

Also, the console prints a couple of warnings:
<img width="922" alt="Screen Shot 2019-06-17 at 14 25 36" src="https://user-images.githubusercontent.com/3537470/59604233-db371a00-910b-11e9-8e8f-7d7d95a32cae.png">

We are not having this issue when we use a standard CRA.

**Comment by F1LT3R** [comment]
Do you have a repo with this setup that I can look at?

**Comment by marcelmika** [comment]
Sure, check the `feature/firebase` branch:
https://github.com/marcelmika/react-workspaces-playground/tree/feature/firebase

Here's the diff:
https://github.com/react-workspaces/react-workspaces-playground/compare/master...marcelmika:feature/firebase

**Comment by F1LT3R** [comment]
It seems like a Webpack issue. If you use the same version of CRA w/o react-workspaces-playground, does firebase still have the same issue? (Ie: possible incompatible versions of Create React App and Firebase)

**Comment by WayneEllery** [comment]
I’m having the same issue. Firebase works with CRA w/o react-workspaces-playground

**Comment by F1LT3R** [comment]
@marcelmika - I get a lot of errors when I try to run `yarn` on your repo. I don't get these with the normal React Workspaces Playground repo that is currently on master.

Do you have a repo where this is working with CRA-only?

When I try to run your code from `yarn start` in `app-one`, I see your util error, but I also see a firebase dependency is missing.

![CleanShot 2019-12-22 at 23 15 33@2x](https://user-images.githubusercontent.com/1218446/71335499-ff3b4400-2510-11ea-86f3-d2bfa37ba680.png)

![CleanShot 2019-12-22 at 23 16 26@2x](https://user-images.githubusercontent.com/1218446/71335552-36115a00-2511-11ea-9331-83eb7cb52ebb.png)

**Comment by F1LT3R** [comment]
Things I tried that did not work:

1. Installing latest Firebase
2. Removing `node_modules` and `yarn.lock` then re-installing

**Comment by F1LT3R** [comment]
I'm able to get a different set of errors when using hoisting for firebase in the root workspace `package.json`. I'm thinking there's a conflict that we can get around by hoisting correctly. Updating the to latest CRA may help.
 
<img width="712" alt="CleanShot 2019-12-22 at 23 42 18@2x" src="https://user-images.githubusercontent.com/1218446/71336386-f187bd80-2514-11ea-9c2e-e4d049bfe1e7.png">

**Comment by F1LT3R** [comment]
I will try to check Firebase again soon. It may "just work" after updating to latest React v3.3.0. That update work is being done here: https://github.com/react-workspaces/react-workspaces-playground/pull/21
