### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by HaswinVidanage** [react-workspaces/react-workspaces-playground#11]
Does it support for React Native if not any plans for it?

**Comment by juanlu78** [comment]
Im on the same page. It would be interesting if we could have components to reuse in reactive-native apps.

**Comment by AlvSovereign** [comment]
Any joy with this?

**Comment by F1LT3R** [comment]
I think it would be great to have React Native supported.

Anyone with RN experience want to try making a PR for this?

(My only RN experience is a RN tutorial about 4 years ago).
