### ISSUE TITLE
Numerous issues on Windows with VS Code

### ISSUE THREAD

**Issue by fsjsd** [react-workspaces/react-workspaces-playground#12]
Tried following the instructions, this doesn't work in VS Code:

> git clone git@github.com:react-workspaces/cra-workspaces-playground

error:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

So tried a straight git clone of :

```https://github.com/react-workspaces/react-workspaces-playground/```

... then followed by ```yarn``` as per instructions.

yarn start in the app-one folder doesn't work so I ran ```yarn``` in that folder to (presumably) pull in / link dependencies which changed the error, then got:

```
Module not found: Can't resolve '@project/components' in 'C:\_src\react-workspaces\packages\apps\app-one\src'
```

tried a ```yarn build``` in the component directory but that failed as well:

```
Could not find a required file.
  Name: index.html
```

**Comment by diogoweb2** [comment]
same...

If it's not Windows compatible, pls add to the doc.

**Comment by F1LT3R** [comment]
@diogoweb2 @fsjsd - would you like to PR?
