### ISSUE TITLE
install from CI

### ISSUE THREAD

**Issue by NookieGrey** [react-workspaces/react-workspaces-playground#16]
is it any opportunity to create installer to avoid git history and fixed repo name?

**Comment by F1LT3R** [comment]
installer?
how do you envision this working?

**Comment by NugzarGaguliya** [comment]
when we creating repo with CRA, we write 'npx create-react-app repo-name' with our repo name and only one commit in git history

**Comment by F1LT3R** [comment]
What are you doing now that is giving you other history?

Are you using this command?

```bash
create-react-app --scripts-version @react-workspaces/react-scripts my-app
```

**Comment by NookieGrey** [comment]
I'm talking about full monorepo, not inside app

**Comment by F1LT3R** [comment]
`sudo rm -r .git` etc... ?

**Comment by F1LT3R** [comment]
Maybe you are talking about a generator for the whole repo?

Why not just git clone shallow?

**Comment by NookieGrey** [comment]
Yes, it's many workarounds, but standard is use one npm or npx command, it just simplifying. If you not think so, just close this issue.

**Comment by NookieGrey** [comment]
ok, thanks
