### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by andrewmclagan** [react-workspaces/react-workspaces-playground#17]
> -- This issue is theory and has not been tested --

From a first inspection of this monorepo setup it seems that `components` would not be tree shakable. Importing `<CompOne />` also imports `<CompTwo />` as there is nothing specifying webpack (any bundler) should do otherwise. 

If we have two apps that both use components, and only need to use portions of these components, we have allot of dead code. In any real-world app/team not all components would be used.

Prime use-case for [sideEffects](https://webpack.js.org/guides/tree-shaking).

Im making allot of assumptions:
* `react-scripts` does not have optimisations for transpiling/building packages.
* `react-scripts` does not transpile modules in `node_modules`

**Comment by Jordan-Gilliam** [comment]
@andrewmclagan do you know if this project is still being maintained?

**Comment by F1LT3R** [comment]
I tried tree-shaking with this a while back, and it worked. 
Have you checked the output of the build?

**Comment by F1LT3R** [comment]
@andrewmclagan - I tested tree shaking just now and it still seems to work just fine.

![CleanShot 2019-12-22 at 22 16 33@2x](https://user-images.githubusercontent.com/1218446/71333773-5b9a6580-2509-11ea-9074-8d5aae4e6d98.png)

**Comment by F1LT3R** [comment]
Anyone: feel free to reopen this if you find a case where tree-shaking is not working.

**Comment by dangnelson** [comment]
I'm experiencing an issue where a dependency that a shared component needs will be included in the projects that don't use that component. 

So if CompOne imports `some-package` then that package gets included in the build for `some-app` even though CompOne isn't used by `some-app`.
