### ISSUE TITLE
README.md incorrect git url

### ISSUE THREAD

**Issue by DavidSun0403** [react-workspaces/react-workspaces-playground#20]
Installation
git clone git@github.com:react-workspaces/cra-workspaces-playground

the url should be git@github.com:react-workspaces/react-workspaces-playground.git

**Comment by F1LT3R** [comment]
Thanks @DavidSun0403 !

**Comment by F1LT3R** [comment]
Fixed: https://github.com/react-workspaces/react-workspaces-playground/blame/master/README.md#L39
