### ISSUE TITLE
Diff in README is outdated

### ISSUE THREAD

**Issue by PaulRBerg** [react-workspaces/react-workspaces-playground#26]
I was reading the README and stopped at this:

<img width="765" alt="Capture d’écran 2020-01-07 à 17 00 13" src="https://user-images.githubusercontent.com/8782666/71904647-2e87bd00-316f-11ea-95a0-97cd3f8a840f.png">

But this doesn't seem to reflect the latest changes to the `yarn-workspaces.js` file:

https://github.com/react-workspaces/create-react-app/commit/a498a364abe1a1bf8486d2d9fcfbda5ab47dc856#diff-dc0c4e7c623b73660da1809fc60cf6ba

**Comment by F1LT3R** [comment]
Thanks @PaulRBerg - I will try and update this soon.

Please PR if you feel this is urgent.
