### ISSUE TITLE
Update to react-scripts 2.1.5?

### ISSUE THREAD

**Issue by EZEDSEA** [react-workspaces/react-workspaces-playground#3]
Any chance for an upgrade to the latest react-scripts 2.1.5?

**Comment by F1LT3R** [comment]
Yes, this is something I'm looking to do within the next week.

Watch this space...

**Comment by EZEDSEA** [comment]
I ended up just copying your code over into the 2.1.5 react-scripts code and it seems to work.

The only thing that doesn't seem to work for me right now is if I want typescript support with the components.  Have you had any lucky with that in the past?

**Comment by alistair-hmh** [comment]
@EZEDSEA , I upgraded react-scripts 3.0.0. Can you confirm this works for you?

If you go typescript, you might have to do it for the whole repo as it may have conflicting babel/etc. versions. It's probably possible to mix both, but it could be tricky to get the initial setup working with the right hoisting rules, etc.
