### ISSUE TITLE
Add support to Sass 

### ISSUE THREAD

**Issue by RamWebDev** [react-workspaces/react-workspaces-playground#31]
When the Component or App gets complex, it is easier to use Sass than plain CSS.
Please add support for Sass

**Comment by MikeSuiter** [comment]
Have to tried to add SASS? I would think anything you can do with CRA 3 you can do with react-workspaces.

https://create-react-app.dev/docs/adding-a-sass-stylesheet/

**Comment by RamWebDev** [comment]
Thanks. It works fine.
