### ISSUE TITLE
Unable to consume typescript classes in components-typescript

### ISSUE THREAD

**Issue by RamWebDev** [react-workspaces/react-workspaces-playground#39]
I have a typescript class called "HelloWorld.ts" added to "components-typescript" project under "components-typescript/src/library" folder
"HelloWorld.ts" file is attached

[HelloWorld.txt](https://github.com/react-workspaces/react-workspaces-playground/files/4231092/HelloWorld.txt)

And I have getting below mentioned error
![TypeScriptError](https://user-images.githubusercontent.com/16088067/74940271-2c27ac80-5417-11ea-9c21-54a0d88e1f47.png)

Please let me know if you need any more details.
@F1LT3R , @PaulRBerg , @jmyrland

**Comment by keshikashviligio** [comment]
> I have a typescript class called "HelloWorld.ts" added to "components-typescript" project under "components-typescript/src/library" folder
> "HelloWorld.ts" file is attached
> 
> [HelloWorld.txt](https://github.com/react-workspaces/react-workspaces-playground/files/4231092/HelloWorld.txt)
> 
> And I have getting below mentioned error
> ![TypeScriptError](https://user-images.githubusercontent.com/16088067/74940271-2c27ac80-5417-11ea-9c21-54a0d88e1f47.png)
> 
> Please let me know if you need any more details.
> @F1LT3R , @PaulRBerg , @jmyrland

Paste this: EXTEND_ESLINT=true variable in app-typescript .env file, if you don't have .env created and restart app

**Comment by RamWebDev** [comment]
Thanks @keshikashviligio . 
It works with the changes you suggested.
Same has to be done for storybook-typescript as well
