### ISSUE TITLE
react-create-app, antd, typescript

### ISSUE THREAD

**Issue by konrad-marzec** [react-workspaces/react-workspaces-playground#41]
I tried `react-app-rewired` with `customize-cra` to configure `antd`. `yarn start:app-ts` fails with error.
https://aleksandrhovhannisyan.github.io/blog/dev/how-to-set-up-react-typescript-ant-design-less-css-modules-and-eslint/

```
Module parse failed: Unexpected token (4:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import './CompOne.css';
| 
> const CompOne: React.FC = () => {
|   return (
|     <div className="Comp">

```

**Comment by F1LT3R** [comment]
Did you try from the existing demo in this repository?  Or did you start from scratch?

**Comment by F1LT3R** [comment]
Closing as no response. Feel free to reopen if you want me to help debug.

**Comment by acestudiooleg** [comment]
same situation
