### ISSUE TITLE
Upgrade react-scripts to 3.4.1

### ISSUE THREAD

**Issue by joe-rocko** [react-workspaces/react-workspaces-playground#42]
create-react-app released [new version](https://github.com/facebook/create-react-app/releases/tag/v3.4.1) which increments babel to [version 7.9](https://babeljs.io/blog/2020/03/16/7.9.0)

**Comment by alanrubin** [comment]
Unfortunately, there seems to be depending on #35 which is blocked at the moment

**Comment by F1LT3R** [comment]
Published version @react-workspaces/react-scripts version 3.4.0-alpha-01.

Does that take care of it?

FYI: Feel free to join me on Slack if you need a faster response.

https://join.slack.com/t/react-workspaces/shared_invite/zt-dx88pvp1-qUphnsiM7CmF2ll0wo_sPA
