### ISSUE TITLE
Typescript compatibility

### ISSUE THREAD

**Issue by nloding** [react-workspaces/react-workspaces-playground#6]
I'd really love to see this working with Typescript. My next big project, I'm hoping, will be a monorepo with 2-3 React apps, a couple backend services with an API, all in Typescript. I haven't looked at how you are running this yet, but wanted to start a thread to track it. Hopefully it's "simple"!

**Comment by F1LT3R** [comment]
So long as your packages are sharing the same CRA config, Typescript should be possible. I've not used storybook in a TS project before, so that may take a little work. That being said, Storybook has the SB --init command, which in theory should auto-configure storybook to work alongside your CRA config.

Thanks for the suggestion, we should def. get as TS version running ASAP.

**Comment by huyuplift** [comment]
Any suggestions on how to get started on making this work for TypeScript?

**Comment by nloding** [comment]
I haven't had time to start on this yet ... but I am still planning on doing a monorepo with Typescript for my next project.

**Comment by comerc** [comment]
@F1LT3R :1st_place_medal: I simplified your code and released CRA without fork or eject as host monorepo package. With rollup as bandler for packages. With Typescript compatibility. [Enjoy](https://github.com/comerc/minsk4)

**Comment by Draer** [comment]
> @F1LT3R 🥇 I simplified your code and released CRA without fork or eject as host monorepo package. With rollup as bandler for packages. With Typescript compatibility. [Enjoy](https://github.com/comerc/minsk4)

But how can you then work with many CRA apps?

**Comment by ReasonableDeveloper** [comment]
I think this PR https://github.com/react-workspaces/create-react-app/pull/3 will enable nice TypeScript support. Can't wait to use `react-workspaces` as I'm currently running my own typescript configuration which breaks on every `react-scripts` release 😭

**Comment by neilime** [comment]
Is there any chance that this issue will be fixed ? I've try the PR https://github.com/react-workspaces/create-react-app/pull/3, and it works like a charm.

Typescript is used more and more frequently, it is missing for react-workspaces

**Comment by abrkn** [comment]
@neilime Are you able to use TS code in the components library? https://github.com/cmsd2/react-workspaces-playground/pull/1

**Comment by abrkn** [comment]
> I haven't had time to start on this yet ... but I am still planning on doing a monorepo with Typescript for my next project.

Did you?

**Comment by abrkn** [comment]
> > @F1LT3R 🥇 I simplified your code and released CRA without fork or eject as host monorepo package. With rollup as bandler for packages. With Typescript compatibility. [Enjoy](https://github.com/comerc/minsk4)
> 
> But how can you then work with many CRA apps?

Same issue. @comerc example does not help with multiple CRA.

**Comment by F1LT3R** [comment]
> Same issue. @comerc example does not help with multiple CRA. - @abrkn 

I've been working on adding TypeScript examples in this PR:
https://github.com/react-workspaces/react-workspaces-playground/pull/21

I've checked Hot-Reloading of the TypeScript components and everything seems to be working well. It should work with multiple CRA apps.
