### ISSUE TITLE
How to create new component library?

### ISSUE THREAD

**Issue by stclairdaniel** [react-workspaces/react-workspaces-playground#7]
I figured it would be as simple as making another directory inside of packages, say `componentsTwo`, adding it to the root `package.json` under `workspace/packages` and then add it to the application `package.json` like `"@project/componentsTwo": "*"`, but I get an error when trying to `yarn install` - `error Couldn't find package "@project/helpers@*" required by "my-app" on the "npm" registry.`

Is this some silly user error?

**Comment by mpress** [comment]
It needs to be another Create React App - so from the root run 
```yarn create react-app packages /componentsTwo```
and you should be able to reference them from your apps.

**Comment by F1LT3R** [comment]
@stclairdaniel did you run `yarn` after updating your Workspaces?

**Comment by stclairdaniel** [comment]
I'm sorry, I should have commented earlier. I did not have a package.json in the second library - I thought some exported components and an index.js was sufficient. Thanks :)
